import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
x = np.linspace(0, 2 * np.pi, 100)
y1 = np.sin(x)
y2 = np.cos(x)
plt.figure()
plt.plot(x, y1, label="sin(x)")
plt.plot(x, y2, label="cos(x)")
plt.title("Funkcje sinus i cosinus")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid()
plt.xlim(0, 2 * np.pi)
plt.xticks(
[0, np.pi / 2, np.pi, 3 * np.pi / 2, 2 * np.pi],
["0", "π/2", "π", "3π/2", "2π"]
)
plt.show()
plt.figure(1)
plt.plot(x, np.sin(x))
plt.title("Wykres sin(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.figure(2)
plt.plot(x, np.cos(x))
plt.title("Wykres cos(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.show()
plt.figure()
plt.subplot(1, 2, 1)
plt.plot(x, np.sin(x))
plt.title("sin(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.subplot(1, 2, 2)
plt.plot(x, np.cos(x))
plt.title("cos(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.tight_layout()
plt.show()
x_scatter = np.random.rand(20) * 10
y_scatter = np.random.rand(20) * 10
plt.figure()
plt.scatter(x_scatter, y_scatter)
plt.title("Wykres punktowy (scatter)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.show()
kategorie = ["A", "B", "C", "D", "E"]
wartosci = [5, 7, 3, 8, 6]
fig, ax = plt.subplots()
bars = ax.bar(kategorie, wartosci)
ax.bar_label(bars)
ax.set_title("Wykres słupkowy")
ax.set_xlabel("Kategorie")
ax.set_ylabel("Wartości")
plt.show()
dane = np.random.randn(1000)
plt.figure()
plt.hist(dane, bins=20, color="purple")
plt.title("Histogram")
plt.xlabel("Wartość")
plt.ylabel("Liczność")
plt.grid()
plt.show()
udzialy = [40, 35, 25]
etykiety = ["A", "B", "C"]
plt.figure()
plt.pie(udzialy, labels=etykiety, autopct="%1.1f%%")
plt.title("Wykres kołowy")
plt.show()